lst1 = ['Mango','Strawberry','Peach','Apple','Orange','Blackberries','BLueberries','Kiwi','Lychee','Banana']
print("Length of the List",len(lst1))
print("First Element",lst1[0])
print("Last Element",lst1[-1])
print("Second Element",lst1[1])
print("Third Element",lst1[2])
print("Fourth Element",lst1[3])
print("Fith Element",lst1[4])
lst1.append('Papaya')
print("updated",lst1)
lst1.remove('Papaya')
print("updated",lst1)
lst1.sort()
print("updated",lst1)
lst1.pop(1)
print("updated",lst1)
lst1.reverse()
print("updated",lst1)
lst1.reverse()
print("updated",lst1)
print(lst1*4)
lst1 = lst1[:4]
print("updated",lst1)
lst1.clear()
print("updated",lst1)
